---
# handlers file for docker

    - name: start docker
      become: yes
      become_method: sudo
      service: name=docker state=started enabled=yes

    - name: restart docker
      become: yes
      service: name=docker state=restarted