---
# tasks file for docker swarm consul instance

- meta: flush_handlers

- name: Add dd-agent user to docker group
  user: name=dd-agent group=docker
  become: yes

- name: run docker consul image
  become: yes
  become_user: docker
  docker:
    name: consul
    image: progrium/consul
    command: -server -bootstrap
    ports: 8500:8500
    detach: true
    state: started
    restart_policy: always
  tags:
    - worker
