---
# tasks file to install version control system
- name: install vcs
  become: yes
  yum: name={{ item }}
       state=present
  with_items:
    - git
    - subversion
  tags:
    - install
    - cloud
