---
# tasks file for docker container


  - name: Add docker group
    become: yes
    group: name=docker system=yes state=present

  - name: add docker user
    user: name={{ docker_user }}
          state=present
    become: yes

  - name: Add {{ docker_user }} user to docker group
    user: name={{ docker_user }} group=docker
    become: yes

  # Following code possible in ansible 2.1
  #- name: Add yum repository
  #  yumrepo:
  #    name: Docker Repository
  #    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
  #    enabled: yes
  #    gpgcheck: yes
  #    gpgkey: https://yum.dockerproject.org/gpg

  - name: Add docker repo
    become: yes
    copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

  - name: Instal docker-engine
    become: yes
    yum: name=docker-engine state=latest
    notify: start docker

  - name: create docker image installation directory
    file: path={{ docker_image }} state=directory owner=docker recurse=yes
    become: yes

  - name: add docker image installation to custom docker daemon options
    become: yes
    template: src=../templates/docker.service.j2 dest=/etc/systemd/system/docker.service

  - name: reload
    become: yes
    command: systemctl daemon-reload
    notify: restart docker


