---
# tasks file for docker container

- name: Add docker group
  become: yes
  group: name=docker system=yes state=present
  tags:
    - user
    - worker

- name: add docker user
  user: name={{ docker_user }}
        state=present
  become: yes
  tags:
    - user
    - worker

- name: Add {{ docker_user }} user to docker group
  user: name={{ docker_user }} group=docker
  become: yes
  tags:
    - user
    - worker

- name: set permissions on docker workers directory
  file: path=/data/container/files state=directory owner=django group=docker mode=2775
  become: yes
  become_method: sudo
  tags:
    - install

# Following code possible in ansible 2.1
#- name: Add yum repository
#  yumrepo:
#    name: Docker Repository
#    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
#    enabled: yes
#    gpgcheck: yes
#    gpgkey: https://yum.dockerproject.org/gpg

- name: Add docker repo
  become: yes
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo
  tags:
    - install
    - worker

- name: Install docker-engine
  become: yes
  yum: name=docker-engine state=latest
  notify: start docker
  tags:
    - install
    - worker

- name: create docker image installation directory
  file: path={{ docker_image }} state=directory owner=docker recurse=yes
  become: yes
  tags:
    - install

- name: add docker image installation to custom docker daemon options
  become: yes
  template: src=../templates/docker.service.j2 dest=/etc/systemd/system/docker.service
  tags:
    - configuration
    - worker

- name: reload
  become: yes
  command: systemctl daemon-reload
  notify: restart docker
  tags:
    - service
    - worker

- name: make sure docker is started on boot
  become: yes
  service:  name=docker
            state=started
            enabled=yes
  tags:
    - service
    - worker
