---
# tasks file for roles/ec2
- name: "Create redis machine"
  ec2:
  args:
    key_name: "{{ key_name }}"
    instance_type: t2.small
    image: ami-7abd0209
    wait: yes
    groups: "{{ redis_groups }}"
    region: eu-west-1
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ redis_name }}"
      Project: "1220828"
  tags:
    - redis

- name: "Create celery machine"
  ec2:
  args:
    key_name: "{{ key_name }}"
    instance_type: t2.medium
    image: ami-7abd0209
    wait: yes
    groups: "{{ celery_groups }}"
    region: eu-west-1
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ celery_name }}"
      Project: "1220828"
    volumes:
      - volume_size: 40
        volume_type: gp2
        device_name: /dev/sda1
  tags:
    - celery

- name: "Create docker node machine"
  ec2:
  args:
    key_name: "{{ key_name }}"
    instance_type: t2.medium
    image: ami-7abd0209
    wait: yes
    groups: "{{ docker_node_groups }}"
    region: eu-west-1
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ docker_node_name }}"
      Project: "1220828"
    volumes:
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/sda1
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/xvdb
      - volume_size: 2
        volume_type: gp2
        device_name: /dev/xvdc
  tags:
    - docker_node

- name: "Create docker consul machine"
  ec2:
  args:
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image: ami-7abd0209
    wait: yes
    groups: "{{ docker_consul_groups }}"
    region: eu-west-1
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ docker_consul_name }}"
      Project: "1220828"
    volumes:
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/sda1
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/xvdb
      - volume_size: 2
        volume_type: gp2
        device_name: /dev/xvdc
  tags:
    - docker_consul

- name: "Create docker manage machine"
  ec2:
  args:
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image: ami-7abd0209
    wait: yes
    groups: "{{ docker_manage_groups }}"
    region: eu-west-1
    count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ docker_manage_name }}"
      Project: "1220828"
    volumes:
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/sda1
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/xvdb
      - volume_size: 2
        volume_type: gp2
        device_name: /dev/xvdc
  tags:
    - docker_manage


- name: Create AMI for docker swarm
  ec2_ami:
    name: "{{ ami_name }}"
    description: "docker swarm node image"
    device_mapping:
      - device_name: /dev/sda1
        size: 8
        delete_on_termination: true
        volume_type: gp2
    tags:
      Name: "docker_swarm"
      Project: "1220828"
    instance_id: "{{ instance_id }}"
    wait: yes
    state: present
    region: eu-west-1
  tags:
    - docker_ami

- name: terminate docker swarm instance
  ec2:
    instance_ids: "{{ instance_id }}"
    region: eu-west-1
    state: absent
  tags:
    - docker_ami

- name: create launch configuration
  ec2_lc:
    name: "{{ launch_conf_name }}"
    image_id: "{{ launch_conf_img_id }}"
    instance_type: c4.large
    region: eu-west-1
    security_groups: "{{ docker_launch_groups }}"
    state: present
    user_data: |
                #!/bin/bash
                mkdir /data/container/files
                echo "eu-west-1b.{{ efs_id }}.efs.eu-west-1.amazonaws.com:/ /data/container/files/ nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0" >> /etc/fstab
                mount -a -t nfs4
                rm -f /etc/docker/key.json
                systemctl restart docker
                DD_API_KEY=93eabbe1921512b173b6dee1d2c4c758 bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"
                usermod -a -G docker dd-agent
                cp /etc/dd-agent/conf.d/docker_daemon.yaml.example /etc/dd-agent/conf.d/docker_daemon.yaml
                systemctl restart datadog-agent
                runuser -l  docker -c "docker run -d swarm join --advertise=$(ip route get 8.8.8.8 | awk '/8.8.8.8/ {print $NF}'):2375 consul://{{ docker_consul_private_ip }}:8500"
    key_name: "{{ key_name }}"
    volumes:
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/sda1
      - volume_size: 8
        volume_type: gp2
        device_name: /dev/xvdb
      - volume_size: 2
        volume_type: gp2
        device_name: /dev/xvdc
  tags:
    - launch_conf

- name: create auto scaling group
  ec2_asg:
    availability_zones: eu-west-1b
    desired_capacity: "{{ desired }}"
    launch_config_name: "{{ launch_conf_name }}"
    max_size: "{{ max }}"
    min_size: "{{ min }}"
    name: "{{ auto_scale_name }}"
    region: eu-west-1
    state: present
    tags:
      - Name: "{{ node_name }}"
      - Project: "1220828"
    wait_for_instances: yes
  tags:
    - auto_scale




